
USE pluginDatabase;

CREATE TABLE IF NOT EXISTS plugins (
	`id` VARCHAR(64) NOT NULL,
	PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE plugins ADD `name`       VARCHAR(64) NOT NULL;
ALTER TABLE plugins ADD `enabled`    BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE plugins ADD `version`    VARCHAR(32) NOT NULL;
ALTER TABLE plugins ADD `authors`    VARCHAR(64) NOT NULL;
ALTER TABLE plugins ADD `desc`       VARCHAR(256) DEFAULT '' NOT NULL;
ALTER TABLE plugins ADD `desc_zhCN`  VARCHAR(256) DEFAULT '' NOT NULL;
ALTER TABLE plugins ADD `repo`       VARCHAR(256) DEFAULT '' NOT NULL;
ALTER TABLE plugins ADD `link`       VARCHAR(256) DEFAULT '' NOT NULL;
ALTER TABLE plugins ADD `lastUpdate` DATETIME DEFAULT NULL;

-- labels
ALTER TABLE plugins ADD `label_information` BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE plugins ADD `label_tool` BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE plugins ADD `label_management` BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE plugins ADD `label_api` BOOLEAN DEFAULT FALSE NOT NULL;

ALTER TABLE plugins ADD `github_sync` BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE plugins ADD `last_sync` DATETIME DEFAULT NULL;
