# syntax=docker/dockerfile:1.2

ARG GO_VERSION=1.20
ARG REPO=github.com/kmcsr/PluginWebPoint
ARG SUB_FOLDER=cmds/plugin_web_point
ARG OUT_NAME=application

FROM golang:${GO_VERSION}-alpine AS BUILD

ARG NPM_DIR=vue-project
ARG REPO
ARG SUB_FOLDER
ARG OUT_NAME

COPY ./go.mod ./go.sum "/go/src/${REPO}/"
COPY "./api" "/go/src/${REPO}/api"
COPY "./$SUB_FOLDER" "/go/src/${REPO}/${SUB_FOLDER}"
COPY "./${NPM_DIR}/dist" "/go/src/${REPO}/${SUB_FOLDER}/dist"
RUN --mount=type=cache,target=/root/.cache/go-build cd "/go/src/${REPO}" && \
 CGO_ENABLED=0 go build -v -o "/go/bin/${OUT_NAME}" "./${SUB_FOLDER}"

FROM alpine:latest

ARG OUT_NAME

COPY --from=BUILD "/go/bin/${OUT_NAME}" "/${OUT_NAME}"

CMD exec "/${OUT_NAME}"
