# syntax=docker/dockerfile:1

ARG NODE_VERSION=20
ARG NPM_DIR=vue-project

FROM node:${NODE_VERSION}-alpine

WORKDIR /app

ARG NPM_DIR

COPY ["${NPM_DIR}/package.json", "${NPM_DIR}/package-lock.json", "./"]
RUN --mount=type=cache,target=/root/.npm/_cacache \
 npm ci --prefer-offline --progress=false || { cat /root/.npm/_logs/*; exit 1; }

COPY "${NPM_DIR}/" "./"

ENV NODE_ENV=development

CMD ["npm", "run", "dev", "80"]
