
name: Create tagged release

on:
  push:
    tags:
      - 'v*'

jobs:
  release-docker-images:
    runs-on: ubuntu-latest
    steps:
      -
        name: Action Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build docker images
        env:
          PUBLIC_PREFIX: craftmine/server-installer
          TAG: ${{ github.ref }}
        run: /usr/bin/env bash ./docker/build.sh
